disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - implicit_getter
  - legacy_constructor
  - empty_enum_arguments
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules: # some rules are only opt-in
  - empty_count
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

warning_threshold: 50
todo: warning
identifier_name:
  min_length: 2
line_length:
  - 200 # warning
  - 300 # error
function_parameter_count:
  - 5
large_tuple:
  - 4
  - 6
function_body_length:
  - 45
  - 80
